<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MobileSeeder extends Seeder
{
    public function run(): void
    {
        $mobiles = [

            // 🔴 VERY LOW
            [
                'name' => 'Samsung Galaxy A05',
                'brand' => 'Samsung',
                'price' => 100.99,
                'ram' => 3,
                'storage' => 32,
                'battery' => 5000,
                'screen_size' => 6.50,
                'camera' => 13,
                'processor' => 'Exynos 850',
                'os' => 'Android 13',
                'image_url' => '/images/samsung-galaxy-a05.jfif',
                'ram_mb' => 3072,
                'bluetooth' => 1,
                'clock_speed' => 1.8,
                'dual_sim' => 1,
                'front_camera' => 5,
                'four_g' => 1,
                'mobile_depth' => 0.8,
                'mobile_wt' => 195,
                'n_cores' => 4,
                'px_height' => 720,
                'px_width' => 1600,
                'sc_h' => 15,
                'sc_w' => 7,
                'talk_time' => 18,
                'three_g' => 1,
                'touch_screen' => 1,
                'wifi' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Xiaomi Redmi A2',
                'brand' => 'Xiaomi',
                'price' => 99.99,
                'ram' => 2,
                'storage' => 32,
                'battery' => 5000,
                'screen_size' => 6.52,
                'camera' => 8,
                'processor' => 'Helio G36',
                'os' => 'Android 13 Go',
                'image_url' => '/images/xiaomi-redmi-a2.jfif',
                'ram_mb' => 2048,
                'bluetooth' => 1,
                'clock_speed' => 1.6,
                'dual_sim' => 1,
                'front_camera' => 5,
                'four_g' => 1,
                'mobile_depth' => 0.9,
                'mobile_wt' => 190,
                'n_cores' => 4,
                'px_height' => 720,
                'px_width' => 1600,
                'sc_h' => 15,
                'sc_w' => 7,
                'talk_time' => 16,
                'three_g' => 1,
                'touch_screen' => 1,
                'wifi' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Samsung Galaxy A04',
                'brand' => 'Samsung',
                'price' => 90.99,
                'ram' => 3,
                'storage' => 32,
                'battery' => 5000,
                'screen_size' => 6.50,
                'camera' => 13,
                'processor' => 'Exynos 850',
                'os' => 'Android 12',
                'image_url' => '/images/samsung-galaxy-a04.webp',
                'ram_mb' => 3072,
                'bluetooth' => 1,
                'clock_speed' => 1.7,
                'dual_sim' => 1,
                'front_camera' => 5,
                'four_g' => 1,
                'mobile_depth' => 0.9,
                'mobile_wt' => 192,
                'n_cores' => 4,
                'px_height' => 720,
                'px_width' => 1600,
                'sc_h' => 15,
                'sc_w' => 7,
                'talk_time' => 17,
                'three_g' => 1,
                'touch_screen' => 1,
                'wifi' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 🟠 LOW
            [
                'name' => 'Samsung Galaxy A14',
                'brand' => 'Samsung',
                'price' => 150.99,
                'ram' => 4,
                'storage' => 64,
                'battery' => 5000,
                'screen_size' => 6.60,
                'camera' => 50,
                'processor' => 'Exynos 850',
                'os' => 'Android 13',
                'image_url' => '/images/samsung-galaxy-a14.jfif',
                'ram_mb' => 4096,
                'bluetooth' => 1,
                'clock_speed' => 2.0,
                'dual_sim' => 1,
                'front_camera' => 13,
                'four_g' => 1,
                'mobile_depth' => 0.8,
                'mobile_wt' => 201,
                'n_cores' => 4,
                'px_height' => 1080,
                'px_width' => 2408,
                'sc_h' => 16,
                'sc_w' => 7,
                'talk_time' => 20,
                'three_g' => 1,
                'touch_screen' => 1,
                'wifi' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Xiaomi Redmi 12',
                'brand' => 'Xiaomi',
                'price' => 179.99,
                'ram' => 4,
                'storage' => 128,
                'battery' => 5000,
                'screen_size' => 6.70,
                'camera' => 50,
                'processor' => 'Helio G88',
                'os' => 'Android 13',
                'image_url' => '/images/xiaomi-redmi-12.jfif',
                'ram_mb' => 4096,
                'bluetooth' => 1,
                'clock_speed' => 2.0,
                'dual_sim' => 1,
                'front_camera' => 8,
                'four_g' => 1,
                'mobile_depth' => 0.8,
                'mobile_wt' => 198,
                'n_cores' => 8,
                'px_height' => 1080,
                'px_width' => 2400,
                'sc_h' => 16,
                'sc_w' => 7,
                'talk_time' => 21,
                'three_g' => 1,
                'touch_screen' => 1,
                'wifi' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'OnePlus Nord N30',
                'brand' => 'OnePlus',
                'price' => 229.99,
                'ram' => 6,
                'storage' => 128,
                'battery' => 5000,
                'screen_size' => 6.72,
                'camera' => 50,
                'processor' => 'Snapdragon 695',
                'os' => 'Android 13',
                'image_url' => '/images/oneplus-nord-n30.jfif',
                'ram_mb' => 6144,
                'bluetooth' => 1,
                'clock_speed' => 2.2,
                'dual_sim' => 1,
                'front_camera' => 16,
                'four_g' => 1,
                'mobile_depth' => 0.8,
                'mobile_wt' => 190,
                'n_cores' => 8,
                'px_height' => 1080,
                'px_width' => 2400,
                'sc_h' => 16,
                'sc_w' => 7,
                'talk_time' => 22,
                'three_g' => 1,
                'touch_screen' => 1,
                'wifi' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 🟡 MID
            [
                'name' => 'Samsung Galaxy A34',
                'brand' => 'Samsung',
                'price' => 325.99,
                'ram' => 6,
                'storage' => 128,
                'battery' => 5000,
                'screen_size' => 6.60,
                'camera' => 48,
                'processor' => 'Dimensity 1080',
                'os' => 'Android 14',
                'image_url' => '/images/samsung-galaxy-a34.webp',
                'ram_mb' => 6144,
                'bluetooth' => 1,
                'clock_speed' => 2.6,
                'dual_sim' => 1,
                'front_camera' => 13,
                'four_g' => 1,
                'mobile_depth' => 0.7,
                'mobile_wt' => 199,
                'n_cores' => 8,
                'px_height' => 1080,
                'px_width' => 2340,
                'sc_h' => 16,
                'sc_w' => 7,
                'talk_time' => 24,
                'three_g' => 1,
                'touch_screen' => 1,
                'wifi' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Xiaomi Redmi Note 12',
                'brand' => 'Xiaomi',
                'price' => 200.99,
                'ram' => 6,
                'storage' => 128,
                'battery' => 5000,
                'screen_size' => 6.67,
                'camera' => 48,
                'processor' => 'Snapdragon 685',
                'os' => 'Android 13',
                'image_url' => '/images/xiaomi-redmi-note-12.webp',
                'ram_mb' => 6144,
                'bluetooth' => 1,
                'clock_speed' => 2.4,
                'dual_sim' => 1,
                'front_camera' => 13,
                'four_g' => 1,
                'mobile_depth' => 0.8,
                'mobile_wt' => 189,
                'n_cores' => 8,
                'px_height' => 1080,
                'px_width' => 2400,
                'sc_h' => 16,
                'sc_w' => 7,
                'talk_time' => 23,
                'three_g' => 1,
                'touch_screen' => 1,
                'wifi' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Google Pixel 7a',
                'brand' => 'Google',
                'price' => 399.99,
                'ram' => 8,
                'storage' => 128,
                'battery' => 4385,
                'screen_size' => 6.10,
                'camera' => 64,
                'processor' => 'Tensor G2',
                'os' => 'Android 14',
                'image_url' => '/images/google-pixel-7a.jfif',
                'ram_mb' => 8192,
                'bluetooth' => 1,
                'clock_speed' => 2.8,
                'dual_sim' => 0,
                'front_camera' => 13,
                'four_g' => 1,
                'mobile_depth' => 0.7,
                'mobile_wt' => 193,
                'n_cores' => 8,
                'px_height' => 1080,
                'px_width' => 2400,
                'sc_h' => 15,
                'sc_w' => 7,
                'talk_time' => 20,
                'three_g' => 1,
                'touch_screen' => 1,
                'wifi' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 🟣 HIGH
            [
                'name' => 'Samsung Galaxy S23 FE',
                'brand' => 'Samsung',
                'price' => 600.99,
                'ram' => 8,
                'storage' => 256,
                'battery' => 4500,
                'screen_size' => 6.40,
                'camera' => 50,
                'processor' => 'Exynos 2200',
                'os' => 'Android 14',
                'image_url' => '/images/samsung-galaxy-s23-fe.webp',
                'ram_mb' => 8192,
                'bluetooth' => 1,
                'clock_speed' => 3.0,
                'dual_sim' => 1,
                'front_camera' => 10,
                'four_g' => 1,
                'mobile_depth' => 0.7,
                'mobile_wt' => 209,
                'n_cores' => 8,
                'px_height' => 1080,
                'px_width' => 2340,
                'sc_h' => 16,
                'sc_w' => 7,
                'talk_time' => 25,
                'three_g' => 1,
                'touch_screen' => 1,
                'wifi' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ➕ MID HIGH / HIGH
            [
                'name' => 'OnePlus Nord 3',
                'brand' => 'OnePlus',
                'price' => 350.99,
                'ram' => 8,
                'storage' => 256,
                'battery' => 5000,
                'screen_size' => 6.74,
                'camera' => 50,
                'processor' => 'Dimensity 9000',
                'os' => 'Android 14',
                'image_url' => '/images/oneplus-nord-3.jfif',
                'ram_mb' => 8192,
                'bluetooth' => 1,
                'clock_speed' => 3.0,
                'dual_sim' => 1,
                'front_camera' => 16,
                'four_g' => 1,
                'mobile_depth' => 0.7,
                'mobile_wt' => 193,
                'n_cores' => 8,
                'px_height' => 1240,
                'px_width' => 2772,
                'sc_h' => 16,
                'sc_w' => 7,
                'talk_time' => 26,
                'three_g' => 1,
                'touch_screen' => 1,
                'wifi' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Samsung Galaxy A54',
                'brand' => 'Samsung',
                'price' => 400.99,
                'ram' => 8,
                'storage' => 128,
                'battery' => 5000,
                'screen_size' => 6.40,
                'camera' => 50,
                'processor' => 'Exynos 1380',
                'os' => 'Android 13',
                'image_url' => '/images/samsung-galaxy-a54.webp',
                'ram_mb' => 8192,
                'bluetooth' => 1,
                'clock_speed' => 2.4,
                'dual_sim' => 1,
                'front_camera' => 32,
                'four_g' => 1,
                'mobile_depth' => 0.8,
                'mobile_wt' => 202,
                'n_cores' => 8,
                'px_height' => 1080,
                'px_width' => 2340,
                'sc_h' => 16,
                'sc_w' => 7,
                'talk_time' => 24,
                'three_g' => 1,
                'touch_screen' => 1,
                'wifi' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Xiaomi 13T',
                'brand' => 'Xiaomi',
                'price' => 550.99,
                'ram' => 12,
                'storage' => 256,
                'battery' => 5000,
                'screen_size' => 6.67,
                'camera' => 50,
                'processor' => 'Dimensity 8200 Ultra',
                'os' => 'Android 14',
                'image_url' => '/images/xiaomi-13t.jfif',
                'ram_mb' => 12288,
                'bluetooth' => 1,
                'clock_speed' => 3.1,
                'dual_sim' => 1,
                'front_camera' => 20,
                'four_g' => 1,
                'mobile_depth' => 0.7,
                'mobile_wt' => 193,
                'n_cores' => 8,
                'px_height' => 1220,
                'px_width' => 2712,
                'sc_h' => 16,
                'sc_w' => 7,
                'talk_time' => 28,
                'three_g' => 1,
                'touch_screen' => 1,
                'wifi' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
      
[
    'name' => 'iPhone 15 Pro Max',
    'brand' => 'Apple',
    'price' => 1199.99,
    'ram' => 8,
    'storage' => 256,
    'battery' => 4422,
    'screen_size' => 6.70,
    'camera' => 48,
    'processor' => 'A17 Pro',
    'os' => 'iOS 17',
    'image_url' => '/images/iPhone_15_Pro_Max.jfif',
    'ram_mb' => 8192,
    'bluetooth' => 1,
    'clock_speed' => 3.78,
    'dual_sim' => 1,
    'front_camera' => 12,
    'four_g' => 1,
    'mobile_depth' => 0.8,
    'mobile_wt' => 221,
    'n_cores' => 6,
    'px_height' => 1290,
    'px_width' => 2796,
    'sc_h' => 17,
    'sc_w' => 7,
    'talk_time' => 29,
    'three_g' => 1,
    'touch_screen' => 1,
    'wifi' => 1,
    'created_at' => now(),
    'updated_at' => now(),
],

[
    'name' => 'iPhone 15',
    'brand' => 'Apple',
    'price' => 899.99,
    'ram' => 6,
    'storage' => 128,
    'battery' => 3349,
    'screen_size' => 6.10,
    'camera' => 48,
    'processor' => 'A16 Bionic',
    'os' => 'iOS 17',
    'image_url' => '/images/iPhone_15.webp',
    'ram_mb' => 6144,
    'bluetooth' => 1,
    'clock_speed' => 3.46,
    'dual_sim' => 1,
    'front_camera' => 12,
    'four_g' => 1,
    'mobile_depth' => 0.8,
    'mobile_wt' => 171,
    'n_cores' => 6,
    'px_height' => 1179,
    'px_width' => 2556,
    'sc_h' => 15,
    'sc_w' => 7,
    'talk_time' => 26,
    'three_g' => 1,
    'touch_screen' => 1,
    'wifi' => 1,
    'created_at' => now(),
    'updated_at' => now(),
],
            [
                'name' => 'OnePlus 11R',
                'brand' => 'OnePlus',
                'price' => 420.99,
                'ram' => 8,
                'storage' => 128,
                'battery' => 5000,
                'screen_size' => 6.74,
                'camera' => 50,
                'processor' => 'Snapdragon 8+ Gen 1',
                'os' => 'Android 14',
                'image_url' => '/images/oneplus-11r.jfif',
                'ram_mb' => 8192,
                'bluetooth' => 1,
                'clock_speed' => 3.2,
                'dual_sim' => 1,
                'front_camera' => 16,
                'four_g' => 1,
                'mobile_depth' => 0.7,
                'mobile_wt' => 204,
                'n_cores' => 8,
                'px_height' => 1240,
                'px_width' => 2772,
                'sc_h' => 16,
                'sc_w' => 7,
                'talk_time' => 27,
                'three_g' => 1,
                'touch_screen' => 1,
                'wifi' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Google Pixel 8',
                'brand' => 'Google',
                'price' => 700.99,
                'ram' => 8,
                'storage' => 128,
                'battery' => 4575,
                'screen_size' => 6.20,
                'camera' => 50,
                'processor' => 'Tensor G3',
                'os' => 'Android 14',
                'image_url' => '/images/google-pixel-8.webp',
                'ram_mb' => 8192,
                'bluetooth' => 1,
                'clock_speed' => 3.0,
                'dual_sim' => 0,
                'front_camera' => 10,
                'four_g' => 1,
                'mobile_depth' => 0.7,
                'mobile_wt' => 187,
                'n_cores' => 8,
                'px_height' => 1080,
                'px_width' => 2400,
                'sc_h' => 15,
                'sc_w' => 7,
                'talk_time' => 24,
                'three_g' => 1,
                'touch_screen' => 1,
                'wifi' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Nokia Classic Mini',
                'brand' => 'Nokia',
                'price' => 60.99,
                'ram' => 1,
                'storage' => 4,
                'battery' => 1200,
                'screen_size' => 3.20,
                'camera' => 2,
                'processor' => 'Single Core Basic',
                'os' => 'Nokia OS',
                'image_url' => '/images/nokia-classic-mini.jfif',
                'ram_mb' => 1024,
                'bluetooth' => 0,
                'clock_speed' => 1.0,
                'dual_sim' => 0,
                'front_camera' => 2,
                'four_g' => 0,
                'mobile_depth' => 1.2,
                'mobile_wt' => 140,
                'n_cores' => 1,
                'px_height' => 480,
                'px_width' => 320,
                'sc_h' => 9,
                'sc_w' => 7,
                'talk_time' => 10,
                'three_g' => 0,
                'touch_screen' => 0,
                'wifi' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Samsung Old Basic',
                'brand' => 'Samsung',
                'price' => 89.99,
                'ram' => 1,
                'storage' => 8,
                'battery' => 1500,
                'screen_size' => 4.00,
                'camera' => 5,
                'processor' => 'Basic Dual Core',
                'os' => 'Android 4.4',
                'image_url' => '/images/samsung-old-basic.jfif',
                'ram_mb' => 1103,
                'bluetooth' => 0,
                'clock_speed' => 1.0,
                'dual_sim' => 1,
                'front_camera' => 6,
                'four_g' => 0,
                'mobile_depth' => 2.9,
                'mobile_wt' => 180,
                'n_cores' => 1,
                'px_height' => 990,
                'px_width' => 1486,
                'sc_h' => 8,
                'sc_w' => 7,
                'talk_time' => 16,
                'three_g' => 0,
                'touch_screen' => 1,
                'wifi' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($mobiles as $mobile) {
            DB::table('mobiles')->insert($mobile);
        }
    }
}